<?php

namespace Database\Seeders;

use App\Models\Kantor;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class KantorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Kantor::insert([
            [
                'uuid' => Str::uuid(),
                'kode' => '000',
                'nama' => 'KANTOR PUSAT KSPPS MSI',
                'email' => 'info@kopsyahmsi.com',
                'nomor_telepone' => '02154232925',
                'kantor_pusat' => true,
                'provinsi_id' => '16',
                'kota_kab_id' => '246',
                'kecamatan_id' => '3926',
                'kelurahan_id' => '49548',
                'rt_rw' => null,
                'tanggal_didirikan' => date('Y-m-d',time()),
                'alamat' => 'Grand Batavia Ruko Arcade Blok F No. 52 Jl. Raya Cadas-Kukun kel.Sindangsari Kec.Pasar Kemis Kab.Tangerang Prov.Banten Kode Pos 15560',
            ],
            [
                'uuid' => Str::uuid(),
                'kode' => '001',
                'nama' => 'RAJEG',
                'email' => 'kpcmsi001@kopsyahmsi.com',
                'nomor_telepone' => '082298227071',
                'kantor_pusat' => false,
                'provinsi_id' => '16',
                'kota_kab_id' => '246',
                'kecamatan_id' => '4018',
                'kelurahan_id' => '49482',
                'rt_rw' => '008/004',
                'tanggal_didirikan' => date('Y-m-d',time()),
                'alamat' => 'Kp. Sukabakti Rt/Rw. 008/004 Ds. Lembangsari Kec. Rajeg',
            ],
            [
                'uuid' => Str::uuid(),
                'kode' => '002',
                'nama' => 'TELUKNAGA',
                'email' => 'kpcmsi002@kopsyahmsi.com',
                'nomor_telepone' => '083896553559',
                'kantor_pusat' => false,
                'provinsi_id' => '16',
                'kota_kab_id' => '246',
                'kecamatan_id' => '3895',
                'kelurahan_id' => '50179',
                'rt_rw' => '009/015',
                'tanggal_didirikan' => date('Y-m-d',time()),
                'alamat' => 'Komplek Garuda, blok A1 No.31 RT/RW. 009/015',
            ],
            [
                'uuid' => Str::uuid(),
                'kode' => '003',
                'nama' => 'PAKUHAJI',
                'email' => 'kpcmsi003@kopsyahmsi.com',
                'nomor_telepone' => '02159470639',
                'kantor_pusat' => false,
                'provinsi_id' => '16',
                'kota_kab_id' => '246',
                'kecamatan_id' => '3967',
                'kelurahan_id' => '49663',
                'rt_rw' => '003/003',
                'tanggal_didirikan' => date('Y-m-d',time()),
                'alamat' => 'Jl. Kyai haji syahdulillah RT/RW. 003/003 Kel. Pakuhaji Kec. Pakuhaji',
            ],
            [
                'uuid' => Str::uuid(),
                'kode' => '004',
                'nama' => 'SUKADIRI',
                'email' => 'kpcmsi004@kopsyahmsi.com',
                'nomor_telepone' => '083890519905',
                'kantor_pusat' => false,
                'provinsi_id' => '16',
                'kota_kab_id' => '246',
                'kecamatan_id' => '3968',
                'kelurahan_id' => '50036',
                'rt_rw' => '021/004',
                'tanggal_didirikan' => date('Y-m-d',time()),
                'alamat' => 'Buaran Armaya RT/RW.021/004 Ds. Tegal Kunir Kidul Kec. Mauk',
            ],
            [
                'uuid' => Str::uuid(),
                'kode' => '005',
                'nama' => 'GUNUNG KALER',
                'email' => 'kpcmsi005@kopsyahmsi.com',
                'nomor_telepone' => '083897603112',
                'kantor_pusat' => false,
                'provinsi_id' => '16',
                'kota_kab_id' => '246',
                'kecamatan_id' => '3985',
                'kelurahan_id' => '49166',
                'rt_rw' => '008/004',
                'tanggal_didirikan' => date('Y-m-d',time()),
                'alamat' => 'Kp. Mekar Jaya RT/RW. 008/004 Ds. Cibetok Kec. Gunung Kaler.',
            ],
            [
                'uuid' => Str::uuid(),
                'kode' => '006',
                'nama' => 'KEMIRI',
                'email' => 'kpcmsi006@kopsyahmsi.com',
                'nomor_telepone' => '087883776656',
                'kantor_pusat' => false,
                'provinsi_id' => '16',
                'kota_kab_id' => '246',
                'kecamatan_id' => '4030',
                'kelurahan_id' => '49361',
                'rt_rw' => '003/001',
                'tanggal_didirikan' => date('Y-m-d',time()),
                'alamat' => 'Kp. Kemiri warakas Rt 003/001 Ds. kemiri kec. Kemiri kab. Tangerang',
            ],
            [
                'uuid' => Str::uuid(),
                'kode' => '007',
                'nama' => 'SUKAMULYA',
                'email' => 'kpcmsi007@kopsyahmsi.com',
                'nomor_telepone' => '083804946459',
                'kantor_pusat' => false,
                'provinsi_id' => '16',
                'kota_kab_id' => '246',
                'kecamatan_id' => '3944',
                'kelurahan_id' => '50022',
                'rt_rw' => '004/004',
                'tanggal_didirikan' => date('Y-m-d',time()),
                'alamat' => 'Kp. Tegal Anyar Ds. Sukamulya Kec. Sukamulya (Belakang Sting Pasal Ceplak)',
            ],
            [
                'uuid' => Str::uuid(),
                'kode' => '008',
                'nama' => 'MEKAR BARU',
                'email' => 'kpcmsi008@kopsyahmsi.com',
                'nomor_telepone' => '085715416647',
                'kantor_pusat' => false,
                'provinsi_id' => '16',
                'kota_kab_id' => '246',
                'kecamatan_id' => '3996',
                'kelurahan_id' => '49555',
                'rt_rw' => '004//5',
                'tanggal_didirikan' => date('Y-m-d',time()),
                'alamat' => 'Kp. Tegal Ds. Mekar Baru Kec. MEKAR BARU',
            ],
            [
                'uuid' => Str::uuid(),
                'kode' => '009',
                'nama' => 'SINDANG JAYA',
                'email' => 'kpcmsi009@kopsyahmsi.com',
                'nomor_telepone' => '083897603111',
                'kantor_pusat' => false,
                'provinsi_id' => '16',
                'kota_kab_id' => '246',
                'kecamatan_id' => '3904',
                'kelurahan_id' => '49965',
                'rt_rw' => '004/006',
                'tanggal_didirikan' => date('Y-m-d',time()),
                'alamat' => 'Kp.Sindang Jaya Ds.sindang Jaya Kec.sindang Jaya',
            ],
            [
                'uuid' => Str::uuid(),
                'kode' => '010',
                'nama' => 'TIGARAKSA',
                'email' => 'kpcmsi010@kopsyahmsi.com',
                'nomor_telepone' => '083804946457',
                'kantor_pusat' => false,
                'provinsi_id' => '16',
                'kota_kab_id' => '246',
                'kecamatan_id' => '3923',
                'kelurahan_id' => '50194',
                'rt_rw' => '004/007',
                'tanggal_didirikan' => date('Y-m-d',time()),
                'alamat' => 'Kp. TIGA RAKSA Ds. TIGARAKSA Kec. TIGARAKSA',
            ],
            [
                'uuid' => Str::uuid(),
                'kode' => '011',
                'nama' => 'CISOKA',
                'email' => 'kpcmsi011@kopsyahmsi.com',
                'nomor_telepone' => '083804946458',
                'kantor_pusat' => false,
                'provinsi_id' => '16',
                'kota_kab_id' => '246',
                'kecamatan_id' => '3961',
                'kelurahan_id' => '49067',
                'rt_rw' => '004/008',
                'tanggal_didirikan' => date('Y-m-d',time()),
                'alamat' => 'Kp. CISOKA Ds. CISOKA Kec. CISOKA',
            ],
            [
                'uuid' => Str::uuid(),
                'kode' => '012',
                'nama' => 'MAUK',
                'email' => 'kpcmsi012@kopsyahmsi.com',
                'nomor_telepone' => '083804946458',
                'kantor_pusat' => false,
                'provinsi_id' => '16',
                'kota_kab_id' => '246',
                'kecamatan_id' => '3926',
                'kelurahan_id' => '49548',
                'rt_rw' => '004/009',
                'tanggal_didirikan' => date('Y-m-d',time()),
                'alamat' => 'Kp. MAUK',
            ],
            [
                'uuid' => Str::uuid(),
                'kode' => '013',
                'nama' => 'PANONGAN',
                'email' => 'kpcmsi013@kopsyahmsi.com',
                'nomor_telepone' => '083804946458',
                'kantor_pusat' => false,
                'provinsi_id' => '16',
                'kota_kab_id' => '246',
                'kecamatan_id' => '3977',
                'kelurahan_id' => '49705',
                'rt_rw' => '004/010',
                'tanggal_didirikan' => date('Y-m-d',time()),
                'alamat' => 'Kp. PANONGAN',
            ],
            [
                'uuid' => Str::uuid(),
                'kode' => '014',
                'nama' => 'KRONJO',
                'email' => 'kpcmsi014@kopsyahmsi.com',
                'nomor_telepone' => '083804946458',
                'kantor_pusat' => false,
                'provinsi_id' => '16',
                'kota_kab_id' => '246',
                'kecamatan_id' => '3908',
                'kelurahan_id' => '49427',
                'rt_rw' => '004/011',
                'tanggal_didirikan' => date('Y-m-d',time()),
                'alamat' => 'Kp. KRONJO',
            ],
            [
                'uuid' => Str::uuid(),
                'kode' => '015',
                'nama' => 'SOLEAR',
                'email' => 'kpcmsi015@kopsyahmsi.com',
                'nomor_telepone' => '083804946458',
                'kantor_pusat' => false,
                'provinsi_id' => '16',
                'kota_kab_id' => '246',
                'kecamatan_id' => '4002',
                'kelurahan_id' => '50002',
                'rt_rw' => '004/012',
                'tanggal_didirikan' => date('Y-m-d',time()),
                'alamat' => 'Kp. SOLEAR',
            ],
            [
                'uuid' => Str::uuid(),
                'kode' => '016',
                'nama' => 'KERESEK',
                'email' => 'kpcmsi016@kopsyahmsi.com',
                'nomor_telepone' => '081314697612',
                'kantor_pusat' => false,
                'provinsi_id' => '16',
                'kota_kab_id' => '246',
                'kecamatan_id' => '4027',
                'kelurahan_id' => '49426',
                'rt_rw' => '004/013',
                'tanggal_didirikan' => date('Y-m-d',time()),
                'alamat' => 'Kp.KRESEK Ds.Kresek Kec. Kresek',
            ],
        ]);
    }
}
